/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package PresentacionProgramaAdministrador;

import Persistencia.ConexionBD;
import Persistencia.IConexionBD;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Timestamp;
import javax.swing.JOptionPane;
import javax.swing.event.DocumentEvent;
import javax.swing.event.DocumentListener;
import javax.swing.table.DefaultTableModel;
import java.awt.Font;
import javax.swing.JTable;
import javax.swing.table.JTableHeader;
import javax.swing.table.TableColumnModel;

/**
 *
 * @author Andre
 */
public class frmMonitoreoEquipos extends javax.swing.JFrame {

    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(frmMonitoreoEquipos.class.getName());
    private final IConexionBD conexionBD = new ConexionBD();

    private DefaultTableModel modeloTabla;

    private int paginaActual = 0;
    private int registrosPorPagina = 10;
    private int totalRegistros = 0;

    /**
     * Creates new form frmMenuGestion
     */
    public frmMonitoreoEquipos() {
        initComponents();
        this.setExtendedState(javax.swing.JFrame.MAXIMIZED_BOTH);
        inicializarPantalla();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton2 = new javax.swing.JButton();
        txtTitulo = new javax.swing.JLabel();
        txtSubtitulo = new javax.swing.JLabel();
        txtBusqueda = new javax.swing.JTextField();
        cboFiltro = new javax.swing.JComboBox<>();
        lblFiltro = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblAlumnos = new javax.swing.JTable();
        btnAnterior = new javax.swing.JButton();
        btnSiguiente = new javax.swing.JButton();
        btnRegresar = new javax.swing.JButton();
        lblRegistros = new javax.swing.JLabel();
        cboRegistros = new javax.swing.JComboBox<>();

        jButton2.setBackground(new java.awt.Color(45, 45, 45));
        jButton2.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        jButton2.setForeground(new java.awt.Color(255, 255, 255));
        jButton2.setText("Gestión de Monitoreo de Equipo");
        jButton2.setBorderPainted(false);
        jButton2.setFocusPainted(false);
        jButton2.addActionListener(this::jButton2ActionPerformed);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        txtTitulo.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        txtTitulo.setText("Panel de Administración");

        txtSubtitulo.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        txtSubtitulo.setForeground(new java.awt.Color(153, 153, 153));
        txtSubtitulo.setText("Monitoreo Equipo");

        txtBusqueda.addActionListener(this::txtBusquedaActionPerformed);

        cboFiltro.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Todos", "Máquina", "ID Alumno", "Nombre", "Carrera", "Unidad Académica", "Centro de Cómputo", "Hora Inicio", "Hora Apartado", "Hora Fin" }));

        lblFiltro.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblFiltro.setText("Filtro de Búsqueda");

        tblAlumnos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Maquina", "ID", "Nombre", "Estado", "Carrera", "Unidad Academica", "Centro de Cómputo", "Hora Apartado", "Hora Inicio", "Hora Fin"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tblAlumnos);

        btnAnterior.setText("⬅ Anterior");
        btnAnterior.addActionListener(this::btnAnteriorActionPerformed);

        btnSiguiente.setText("Siguiente ➡");
        btnSiguiente.addActionListener(this::btnSiguienteActionPerformed);

        btnRegresar.setText("Regresar");
        btnRegresar.addActionListener(this::btnRegresarActionPerformed);

        lblRegistros.setText("Cantidad de registros:");

        cboRegistros.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "10", "20", "30", " " }));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(txtSubtitulo)
                                .addGap(106, 106, 106))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(txtBusqueda, javax.swing.GroupLayout.PREFERRED_SIZE, 475, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(15, 15, 15)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(lblFiltro, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(cboFiltro, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGap(51, 51, 51)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 630, Short.MAX_VALUE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btnRegresar)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(lblRegistros)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(cboRegistros, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(9, 9, 9)
                                .addComponent(btnAnterior)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btnSiguiente)))))
                .addGap(43, 43, 43))
            .addGroup(layout.createSequentialGroup()
                .addGap(249, 249, 249)
                .addComponent(txtTitulo)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(txtTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtSubtitulo)
                    .addComponent(lblFiltro))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtBusqueda, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cboFiltro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 237, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAnterior)
                    .addComponent(btnSiguiente)
                    .addComponent(btnRegresar)
                    .addComponent(lblRegistros)
                    .addComponent(cboRegistros, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(27, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
private void inicializarPantalla() {
        modeloTabla = (DefaultTableModel) tblAlumnos.getModel();
        modeloTabla.setRowCount(0);

        txtBusqueda.getDocument().addDocumentListener(new DocumentListener() {
            @Override
            public void insertUpdate(DocumentEvent e) {
                reiniciarYCargar();
            }

            @Override
            public void removeUpdate(DocumentEvent e) {
                reiniciarYCargar();
            }

            @Override
            public void changedUpdate(DocumentEvent e) {
                reiniciarYCargar();
            }
        });

        cboFiltro.addActionListener(e -> reiniciarYCargar());

        cboRegistros.addActionListener(e -> {
            registrosPorPagina = Integer.parseInt(cboRegistros.getSelectedItem().toString());
            reiniciarYCargar();
        });

        cargarPagina();
    }

    private void reiniciarYCargar() {
        paginaActual = 0;
        cargarPagina();
    }

    private void cargarPagina() {
        modeloTabla.setRowCount(0);

        String busqueda = txtBusqueda.getText().trim();
        String where = "";

        if (!busqueda.isEmpty()) {
            where = " WHERE " + obtenerCampoFiltro() + " LIKE ? ";
        }

        String sqlConteo = """
    SELECT COUNT(*) AS total
    FROM alumno a
    LEFT JOIN carrera ca ON a.idCarrera = ca.idCarrera
    LEFT JOIN reserva r ON a.idAlumno = r.idAlumno
    LEFT JOIN computadora c ON r.idComputadora = c.idComputadora
    LEFT JOIN centroComputo cc ON c.idCentroComputo = cc.idCentroComputo
    LEFT JOIN unidadAcademica ua ON cc.idUnidadAcademica = ua.idUnidadAcademica
    """ + where;

        String sqlDatos = """
    SELECT 
        c.numeroMaquina,
        a.idAlumno,
        CONCAT_WS(' ', a.nombre, a.apellidoPaterno, a.apellidoMaterno) AS nombreAlumno,
        a.estatus AS estatusAlumno,
        ca.nombre AS carrera,
        ua.nombre AS unidadAcademica,
        cc.idCentroComputo,
        r.fechaHoraApartado,
        r.fechaHoraInicio,
        r.fechaHoraFinal
    FROM alumno a
    LEFT JOIN carrera ca ON a.idCarrera = ca.idCarrera
    LEFT JOIN reserva r ON a.idAlumno = r.idAlumno
    LEFT JOIN computadora c ON r.idComputadora = c.idComputadora
    LEFT JOIN centroComputo cc ON c.idCentroComputo = cc.idCentroComputo
    LEFT JOIN unidadAcademica ua ON cc.idUnidadAcademica = ua.idUnidadAcademica
    """ + where + """
    ORDER BY r.fechaHoraApartado DESC
    LIMIT ? OFFSET ?
    """;

        try (Connection conexion = conexionBD.crearConexion()) {

            // 1. Obtener el conteo total de registros para la paginación
            try (PreparedStatement psConteo = conexion.prepareStatement(sqlConteo)) {
                if (!busqueda.isEmpty()) {
                    psConteo.setString(1, "%" + busqueda + "%");
                }

                try (ResultSet rs = psConteo.executeQuery()) {
                    if (rs.next()) {
                        totalRegistros = rs.getInt("total");
                    }
                }
            }

            // 2. Obtener los datos paginados
            try (PreparedStatement psDatos = conexion.prepareStatement(sqlDatos)) {
                int parametro = 1;

                if (!busqueda.isEmpty()) {
                    psDatos.setString(parametro++, "%" + busqueda + "%");
                }

                psDatos.setInt(parametro++, registrosPorPagina);
                psDatos.setInt(parametro, paginaActual * registrosPorPagina);

                try (ResultSet rs = psDatos.executeQuery()) {
                    while (rs.next()) {
                        // Se agregan los datos respetando estrictamente el orden del JTable:
                        // [Maquina, ID, Nombre, Estado, Carrera, Unidad Academica, Centro, Apartado, Inicio, Fin]
                        modeloTabla.addRow(new Object[]{
                            rs.getObject("numeroMaquina") != null ? rs.getInt("numeroMaquina") : "", // 1. Maquina
                            rs.getInt("idAlumno"), // 2. ID
                            rs.getString("nombreAlumno"), // 3. Nombre
                            rs.getBoolean("estatusAlumno") ? "Activo" : "Inactivo", // 4. Estado
                            valorONulo(rs.getString("carrera")), // 5. Carrera
                            valorONulo(rs.getString("unidadAcademica")), // 6. Unidad Académica
                            rs.getObject("idCentroComputo") != null ? rs.getInt("idCentroComputo") : "",// 7. Centro de Cómputo
                            formatearFecha(rs.getTimestamp("fechaHoraApartado")), // 8. Hora Apartado
                            formatearFecha(rs.getTimestamp("fechaHoraInicio")), // 9. Hora Inicio
                            formatearFecha(rs.getTimestamp("fechaHoraFinal")) // 10. Hora Fin
                        });
                    }
                }
            }

            // 3. Refrescar estado de botones y etiquetas de la paginación
            actualizarBotonesPaginacion();

        } catch (SQLException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
            JOptionPane.showMessageDialog(
                    this,
                    "Error al cargar los datos:\n" + ex.getMessage(),
                    "Error",
                    JOptionPane.ERROR_MESSAGE
            );
        }
    }

    private String obtenerCampoFiltro() {
        String filtro = cboFiltro.getSelectedItem().toString();

        switch (filtro) {
            case "Todos":
                return """
                       CONCAT_WS(' ',
                       CAST(c.numeroMaquina AS CHAR),
                       CAST(a.idAlumno AS CHAR),
                       a.nombre,
                       a.apellidoPaterno,
                       a.apellidoMaterno,
                       CASE WHEN a.estatus = 1 THEN 'Activo' ELSE 'Inactivo' END,
                       ca.nombre,
                       ua.nombre,
                       CAST(cc.idCentroComputo AS CHAR),
                       DATE_FORMAT(r.fechaHoraInicio, '%Y-%m-%d %H:%i:%s'),
                       DATE_FORMAT(r.fechaHoraApartado, '%Y-%m-%d %H:%i:%s'),
                       DATE_FORMAT(r.fechaHoraFinal, '%Y-%m-%d %H:%i:%s')
                       )
                       """;

            case "Máquina":
                return "CAST(c.numeroMaquina AS CHAR)";

            case "ID Alumno":
                return "CAST(a.idAlumno AS CHAR)";

            case "Nombre":
                return "CONCAT_WS(' ', a.nombre, a.apellidoPaterno, a.apellidoMaterno)";

            case "Estado":
                return "CASE WHEN a.estatus = 1 THEN 'Activo' ELSE 'Inactivo' END";

            case "Carrera":
                return "ca.nombre";

            case "Unidad Académica":
                return "ua.nombre";

            case "Centro de Cómputo":
                return "CAST(cc.idCentroComputo AS CHAR)";

            case "Hora Inicio":
                return "DATE_FORMAT(r.fechaHoraInicio, '%Y-%m-%d %H:%i:%s')";

            case "Hora Apartado":
                return "DATE_FORMAT(r.fechaHoraApartado, '%Y-%m-%d %H:%i:%s')";

            case "Hora Fin":
                return "DATE_FORMAT(r.fechaHoraFinal, '%Y-%m-%d %H:%i:%s')";

            default:
                return "CAST(a.idAlumno AS CHAR)";
        }
    }

    private String formatearFecha(Timestamp fecha) {
        if (fecha == null) {
            return "";
        }

        return fecha.toLocalDateTime().toString().replace("T", " ");
    }

    private String valorONulo(String valor) {
        return valor != null ? valor : "";
    }

    private void actualizarBotonesPaginacion() {
        int totalPaginas = (int) Math.ceil(totalRegistros / (double) registrosPorPagina);

        if (totalPaginas == 0) {
            totalPaginas = 1;
        }

        btnAnterior.setEnabled(paginaActual > 0);
        btnSiguiente.setEnabled((paginaActual + 1) < totalPaginas);

        txtSubtitulo.setText("Gestión Equipo - Página " + (paginaActual + 1) + " de " + totalPaginas);
    }


    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    private void txtBusquedaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtBusquedaActionPerformed
        reiniciarYCargar();
    }//GEN-LAST:event_txtBusquedaActionPerformed

    private void btnAnteriorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAnteriorActionPerformed
        if (paginaActual > 0) {
            paginaActual--;
            cargarPagina();
        }
    }//GEN-LAST:event_btnAnteriorActionPerformed

    private void btnSiguienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSiguienteActionPerformed
        int totalPaginas = (int) Math.ceil(totalRegistros / (double) registrosPorPagina);

        if ((paginaActual + 1) < totalPaginas) {
            paginaActual++;
            cargarPagina();
        }
    }//GEN-LAST:event_btnSiguienteActionPerformed

    private void btnRegresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegresarActionPerformed
        frmMenuGestion ventana = new frmMenuGestion();
        ventana.setVisible(true);
        ventana.setExtendedState(javax.swing.JFrame.MAXIMIZED_BOTH);
        this.dispose();
    }//GEN-LAST:event_btnRegresarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }

        java.awt.EventQueue.invokeLater(() -> new frmMonitoreoEquipos().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAnterior;
    private javax.swing.JButton btnRegresar;
    private javax.swing.JButton btnSiguiente;
    private javax.swing.JComboBox<String> cboFiltro;
    private javax.swing.JComboBox<String> cboRegistros;
    private javax.swing.JButton jButton2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblFiltro;
    private javax.swing.JLabel lblRegistros;
    private javax.swing.JTable tblAlumnos;
    private javax.swing.JTextField txtBusqueda;
    private javax.swing.JLabel txtSubtitulo;
    private javax.swing.JLabel txtTitulo;
    // End of variables declaration//GEN-END:variables
}
